# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    # specify working directory
    # working_directory: ~/public
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16
    steps:
      # cloning git repo
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      # - save_cache:
      #     name: Save Yarn Package Cache
      #     key: yarn-packages-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      - run: yarn build
      - run:
          name: Testing if anything is there
          command: |
            echo $(cat public/index.html)
      - store_artifacts:
          path: public/

  test:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run:
          name: Running Tests
          command: echo "Tested"

  deploy:
    name: Deploy to Linode
    working_directory: ~/{GH-REPO}
    docker:
      - image: circleci/node:10.16
    steps:
      - add_ssh_keys:
          fingerprints:
            - 6d:93:af:14:f2:55:e0:32:4e:9e:9e:4a:32:bc:16:ee
      - run:
          name: Deploy Over SSH
          command: ./deploy.sh

workflows:
  version: 2
  test_build_deploy:
    jobs:
      # - test
      # - build:
      #     requires:
      #       - test
      - deploy
