#!usr/bin/expect

ssh akeem@74.207.224.133

expect "The authenticity of host '74.207.224.133 (74.207.224.133)' can't be established.
ECDSA key fingerprint is SHA256:7HDM2MsXod10sR5PRh4Vls70HEeB+ut1i+O2/7clrNY.
Are you sure you want to continue connecting (yes/no)?"

send -h "yes\r"

expect "akeem@nodejs-api-server"