name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          yarn install
          yarn build
          ls -a
        env:
          CI: true
          CONTENTFUL_SPACE_ID: rhbqbl5xs4xd
          CONTENTFUL_ACCESS_TOKEN: nuWTsHHDypgzrFPiIPKaDEnRR9CB-hXEbTC__Rdqaqw
          ANALYTICS_TRACKING_ID: UA-149886863-1
