name: Building What I Learned Achives

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          yarn install
          yarn build
          ls -a
        env:
          CI: true
          CONTENTFUL_SPACE_ID: rhbqbl5xs4xd
          CONTENTFUL_ACCESS_TOKEN: nuWTsHHDypgzrFPiIPKaDEnRR9CB-hXEbTC__Rdqaqw
          ANALYTICS_TRACKING_ID: UA-149886863-1
      - uses: actions/upload-artifact@v1
        with:
          name: public
          path: public/

  deploy:
    name: Download public file and Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: public
          path: public/
